### ISSUE TITLE
zip_save() misspelling?

### ISSUE THREAD

**Issue by neosoyo** [DARcorporation/xfoil-python#17]
it should be zip_safe?

` 
 Failed building wheel for xfoil
  Running setup.py clean for xfoil
Failed to build xfoil
Installing collected packages: xfoil
  Running setup.py install for xfoil ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tvsij9n5/xfoil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wdq7um9l/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_save'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/xfoil
    copying xfoil/xfoil.py -> build/lib.linux-x86_64-3.7/xfoil
    copying xfoil/test.py -> build/lib.linux-x86_64-3.7/xfoil
    copying xfoil/model.py -> build/lib.linux-x86_64-3.7/xfoil
    copying xfoil/__init__.py -> build/lib.linux-x86_64-3.7/xfoil
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tvsij9n5/xfoil/setup.py", line 149, in <module>
        zip_save=False
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/sbo/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 309, in run
        force=self.force)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "/usr/lib/python3.7/distutils/cygwinccompiler.py", line 293, in __init__
        if self.gcc_version <= "2.91.57":
    TypeError: '<=' not supported between instances of 'NoneType' and 'str'
    
    ----------------------------------------

**Comment by antoniosgeme** [comment]
@neosoyo Were you able to get around this somehow? I am also having trouble building this package.

**Comment by daniel-de-vries** [comment]
Fixed in #18
